### ISSUE TITLE
Maybe it is a mistake.

### ISSUE THREAD

**Issue by lartpang** [huiyang865/plugnet#1]
Great work! Thanks for your contribution.!

Here,

https://github.com/huiyang865/plugnet/blob/d4c3c5f150ee61fb1b9cf1d9bc38ee8081ae3022/lib/models/rcan.py#L103

Maybe it should be like this: `   x = self.tail(res)`

**Comment by huiyang865** [comment]
Yes, it has been fixed. Thanks.

**Comment by minglii1998** [comment]
Hello there, sorry to bother ! @lartpang
Can you reproduce the same accuracy as proposed in the paper? 
My result has a really big gap compared with proposed result and actually I didn't change any configuration (except for some paths) in `main_train.sh`. It really upsets me.

**Comment by lartpang** [comment]
@minglii1998  I'm sorry I can't help you. I didn't try to run this code directly.
I only read the code to refer to the idea of super resolution. 
Regarding the question of accuracy, I suggest you contact the author @huiyang865  directly.
