### ISSUE TITLE
common.MeanShift作用？

### ISSUE THREAD

**Issue by lifailifai** [huiyang865/plugnet#2]
大佬，请问一下，`lib/models/model_builder.py`中先后用到了`x = self.sub_mean(lr)`和`self.add_mean(fake_HR)`，请问这个操作有什么作用？

**Comment by huiyang865** [comment]
self.sub_mean(lr)图片反均一化操作，self.add_mean(fake_HR)图片均一化操作。这里的操作是用来均一化和反均一化，让图片数据和gt保持一致。

**Comment by zhunge** [comment]
> self.sub_mean(lr)图片反均一化操作，self.add_mean(fake_HR)图片均一化操作。这里的操作是用来均一化和反均一化，让图片数据和gt保持一致。

MeanShift继承的nn.Conv2d，纳闷怎么达到均一化？

**Comment by zhunge** [comment]
`lib.datasets.dataset.py`中ResizeNormalize类有gaussian_blur，down_up_sample和contrast三个操作的数据类型未统一

**Comment by zhunge** [comment]
`lib.datasets.dataset.py`中ResizeNormalize类的gaussian_blur，down_up_sample和contrast三个操作的数据类型未统一
