### ISSUE TITLE
关于预训练模型相关

### ISSUE THREAD

**Issue by whuhangzhang** [huiyang865/plugnet#4]
@huiyang865 您好，感谢您优秀的工作和开源了代码。有一些问题想要请教：

1. 是否能提供一下训练好的模型呢？
2. 目前代码的readme实在是过于简单，对于数据的预处理等都没有介绍，能否给一个简单的流程呢？

再次感谢

**Comment by whuhangzhang** [comment]
看起来这个repo是没有维护了，参考如下issue
参考： https://github.com/huiyang865/plugnet/issues/5

**Comment by minglii1998** [comment]
@whuhangzhang 
你好，请问你当时用这个模型达到了大概多少的acc呢？打扰了，谢谢

**Comment by ulanbator** [comment]
你好，打扰了，看您跑通了代码，想知道是否能够提供一份完整的项目代码，我的邮箱是18843426103@163.com，感谢！
